apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/emt_shop
  SPRING_APPLICATION_NAME: emt-2025
  SERVER_PORT: "9090"
  SPRING_PROFILES_ACTIVE: dev
