version: "3.9"

services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: emt
      POSTGRES_PASSWORD: emt
      POSTGRES_DB: emt_shop
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./views.sql:/docker-entrypoint-initdb.d/views.sql
    ports:
      - "2345:5432"

  backend:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/emt_shop
      SPRING_DATASOURCE_USERNAME: emt
      SPRING_DATASOURCE_PASSWORD: emt
    ports:
      - "9090:9090"

  frontend:
    build: ../e-shop-frontend-main
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  pgdata:
