name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Maven Project
    runs-on: ubuntu-latest

    steps:
      # Клонирај го репозиторито
      - uses: actions/checkout@v3

      # Постави JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      # Гради Maven проектот
      - name: Build with Maven
        run: mvn clean install -DskipTests
        working-directory: e-shop-backend-main

  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Клонирај повторно (потребно за секој job)
      - uses: actions/checkout@v3

      # DockerHub login
      - name: DockerHub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/kii-2025:latest .
        working-directory: e-shop-backend-main

      # Push Docker image
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/kii-2025:latest
        working-directory: e-shop-backend-main
